In [1]:
import yfinance as yf
import pandas as pd
import statsmodels
import numpy as np
import datetime
import time
from pandas_datareader import data as pdr
yf.pdr_override()
from statsmodels.tsa.stattools import adfuller
import pandas as pd
import numpy as np
%matplotlib inline
import statistics
import requests #The requests library for HTTP requests in Python
import xlsxwriter #The XlsxWriter libarary for 
import math #The Python math module
from scipy import stats #The SciPy stats module

In [2]:
stocks = pd.read_csv('C:/Users/pconn/Desktop/jupyter_projects/StationarityTickersWeek5.csv')
stocks.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/pconn/Desktop/jupyter_projects/StationarityTickersWeek5.csv'

In [3]:
tickers = list(stocks['Ticker'])

In [4]:
tickers

['ADI',
 'T',
 'ATO',
 'BIIB',
 'COG',
 'KMX',
 'CNP',
 'CI',
 'CSCO',
 'CTXS',
 'CAG',
 'GLW',
 'DG',
 'DTE',
 'ECL',
 'ETR',
 'ETSY',
 'FFIV',
 'FB',
 'F',
 'BEN',
 'GIS',
 'GM',
 'JKHY',
 'SJM',
 'KSU',
 'K',
 'KEYS',
 'MXIM',
 'MOS',
 'MSCI',
 'NDAQ',
 'NKE',
 'NOC',
 'NLOK',
 'NVR',
 'OTIS',
 'PNR',
 'QRVO',
 'TXN',
 'VRSN',
 'WHR',
 'ZBH']

In [5]:
def get(tickers, startdate, enddate):
  def data(ticker):
    return (pdr.get_data_yahoo(ticker, start=startdate, end=enddate))
  datas = map (data, tickers)
  return(pd.concat(datas, keys=tickers, names=['Ticker', 'Date']))

all_data = get(tickers, datetime.datetime(2020, 1, 5), datetime.datetime(2021, 2, 2))

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [6]:
thisdataframe = all_data.reset_index(level='Date', col_level=1)

In [7]:
thisdataframe

,Date,Open,High,Low,Close,Adj Close,Volume
Ticker,,,,,,,
ADI,2020-01-06,116.250000,117.320000,115.610001,116.919998,114.069199,1979400
ADI,2020-01-07,118.900002,120.879997,118.400002,119.580002,116.664337,2214700
ADI,2020-01-08,120.309998,121.459999,119.690002,120.660004,117.718010,2036500
ADI,2020-01-09,121.629997,121.690002,119.739998,120.660004,117.718010,1418500
ADI,2020-01-10,120.800003,120.809998,118.370003,118.570000,115.678970,1610500
...,...,...,...,...,...,...,...
ZBH,2021-01-26,160.250000,161.229996,157.320007,158.220001,158.220001,842600
ZBH,2021-01-27,155.229996,157.720001,152.020004,152.600006,152.600006,1890000
ZBH,2021-01-28,154.199997,159.070007,152.889999,157.029999,157.029999,1540200
ZBH,2021-01-29,156.000000,156.789993,151.850006,153.669998,153.669998,1621500
ZBH,2021-02-01,154.869995,156.009995,152.240005,153.899994,153.899994,1422000

In [8]:
my_columns = ['Ticker','Price','Mean']

In [9]:
final_dataframe = pd.DataFrame(columns = my_columns)

In [11]:
for ticker in tickers:
    data = statistics.mean(thisdataframe.loc[ticker,'Close'])
    print(data)

120.0298525820799
30.87531361456727
100.76774873064893
283.84527723023814
17.909446554430296
90.85501857349354
20.49553506576707
190.984353716523
43.201734338739264
133.4191511653886
34.151365322380485
29.437121704495702
188.50029537862517
115.77586722285984
199.00350529857226
104.06944657779708
105.76747213694442
140.1690037576035
236.94653168287664
7.256346860934888
21.62516602730839
58.981808102878695
31.81523986056282
164.98409606257928
112.18225080764601
167.26483373888306
64.90199220664387
104.82653121666715
67.07324722684177
17.123911410680115
347.544980376409
119.95955680481183
108.9741701217595
324.1920662630088
20.913616236725417
3710.155231095768
59.178386601534754
43.58461251206064
122.2337084555538
134.96099645185294
203.53106987872246
154.13007388519625
135.22612534413918

In [12]:
new_dataframe

NameError: name 'new_dataframe' is not defined

In [10]:
for ticker in tickers:
    batch_api_call_url = f'https://cloud.iexapis.com/stable/stock/market/batch/?types=stats,quote&symbols={ticker}&token=pk_98a9722b99584ee7b7c5ebed778846fc'
    data = requests.get(batch_api_call_url).json()
    data2 = statistics.mean(thisdataframe.loc[ticker, 'Close'])
    final_dataframe = final_dataframe.append(
                                        pd.Series([ticker,
                                                   data[ticker]['quote']['latestPrice']
                                                   [ticker][data2]
                                                   ], 
                                                  index = my_columns), 
                                        ignore_index = True)
        
    
final_dataframe

TypeError: 'float' object is not subscriptable

In [15]:
for ticker in tickers:
    final_dataframe = final_dataframe.append({'Ticker': ticker},ignore_index=True)

In [16]:
final_dataframe

   Ticker Price Mean
0     LNT   NaN  NaN
1     ALL   NaN  NaN
2     AEE   NaN  NaN
3     AON   NaN  NaN
4      BK   NaN  NaN
5     BDX   NaN  NaN
6     BMY   NaN  NaN
7     CPB   NaN  NaN
8     CNC   NaN  NaN
9     CVX   NaN  NaN
10    COP   NaN  NaN
11    CCI   NaN  NaN
12   FANG   NaN  NaN
13      D   NaN  NaN
14    EOG   NaN  NaN
15     ES   NaN  NaN
16    XOM   NaN  NaN
17    FLT   NaN  NaN
18     GD   NaN  NaN
19    IBM   NaN  NaN
20    LHX   NaN  NaN
21    LMT   NaN  NaN
22    MRO   NaN  NaN
23    MRK   NaN  NaN
24   NTRS   NaN  NaN
25   NLOK   NaN  NaN
26   NCLH   NaN  NaN
27    PEP   NaN  NaN
28     PM   NaN  NaN
29    RTX   NaN  NaN
30   SBAC   NaN  NaN
31    SLB   NaN  NaN
32    SRE   NaN  NaN
33    FTI   NaN  NaN
34    TSN   NaN  NaN
35   VRSN   NaN  NaN
36    VNO   NaN  NaN
37    WEC   NaN  NaN
38     WU   NaN  NaN
39   WLTW   NaN  NaN

In [17]:
for ticker in tickers:
    data = statistics.mean(thisdataframe.loc[ticker,'Close'])
    final_dataframe = final_dataframe.append({'Mean': data},ignore_index=True)

In [18]:
final_dataframe

   Ticker Price        Mean
0     LNT   NaN         NaN
1     ALL   NaN         NaN
2     AEE   NaN         NaN
3     AON   NaN         NaN
4      BK   NaN         NaN
..    ...   ...         ...
75    NaN   NaN  203.531070
76    NaN   NaN   41.376347
77    NaN   NaN   93.825129
78    NaN   NaN   22.279410
79    NaN   NaN  199.993432

[80 rows x 3 columns]

In [38]:
meanvalues

[199.99343173882178]