In [1]:
import yfinance as yf
import pandas as pd
import statsmodels
import numpy as np
import datetime
import time
from pandas_datareader import data as pdr
yf.pdr_override()
from statsmodels.tsa.stattools import adfuller
import pandas as pd
import numpy as np
%matplotlib inline
import statistics
import requests #The requests library for HTTP requests in Python
import xlsxwriter #The XlsxWriter libarary for 
import math #The Python math module
from scipy import stats #The SciPy stats module

In [2]:
stocks = pd.read_csv('C:/Users/pconn/Desktop/jupyter_projects/StationarityTickers.csv')
stocks.head()

,Ticker,ADF Statistic,P-Value,1% Interval,5% Interval,10% Interval,Stationarity
0,LNT,-2.893571,0.046101,-3.455853,-2.872765,-2.572752,True
1,ALL,-3.235604,0.018014,-3.455853,-2.872765,-2.572752,True
2,AEE,-2.926207,0.042384,-3.455853,-2.872765,-2.572752,True
3,AON,-3.353430,0.012653,-3.455953,-2.872809,-2.572775,True
4,BK,-3.573865,0.006281,-3.455656,-2.872678,-2.572705,True

In [3]:
tickers = list(stocks['Ticker'])

In [4]:
tickers

['LNT',
 'ALL',
 'AEE',
 'AON',
 'BK',
 'BDX',
 'BMY',
 'CPB',
 'CNC',
 'CVX',
 'COP',
 'CCI',
 'FANG',
 'D',
 'EOG',
 'ES',
 'XOM',
 'FLT',
 'GD',
 'IBM',
 'LHX',
 'LMT',
 'MRO',
 'MRK',
 'NTRS',
 'NLOK',
 'NCLH',
 'PEP',
 'PM',
 'RTX',
 'SBAC',
 'SLB',
 'SRE',
 'FTI',
 'TSN',
 'VRSN',
 'VNO',
 'WEC',
 'WU',
 'WLTW']

In [5]:
def get(tickers, startdate, enddate):
  def data(ticker):
    return (pdr.get_data_yahoo(ticker, start=startdate, end=enddate))
  datas = map (data, tickers)
  return(pd.concat(datas, keys=tickers, names=['Ticker', 'Date']))

all_data = get(tickers, datetime.datetime(2020, 1, 5), datetime.datetime(2021, 2, 4))

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [6]:
thisdataframe = all_data.reset_index(level='Date', col_level=1)

In [7]:
thisdataframe

,Date,Open,High,Low,Close,Adj Close,Volume
Ticker,,,,,,,
LNT,2020-01-06,53.799999,54.119999,53.549999,53.750000,51.840397,2585200
LNT,2020-01-07,53.650002,53.840000,53.320000,53.799999,51.888626,1815100
LNT,2020-01-08,53.820000,54.080002,53.650002,53.919998,52.004360,1504300
LNT,2020-01-09,53.860001,54.590000,53.680000,54.529999,52.592690,1869700
LNT,2020-01-10,54.669998,55.220001,54.570000,55.070000,53.113503,1289200
...,...,...,...,...,...,...,...
WLTW,2021-01-28,206.539993,209.690002,205.860001,206.309998,206.309998,1218600
WLTW,2021-01-29,204.669998,206.389999,202.039993,202.940002,202.940002,1243200
WLTW,2021-02-01,203.940002,209.660004,203.429993,207.449997,207.449997,1137000
WLTW,2021-02-02,205.699997,212.770004,205.699997,211.119995,211.119995,806400
WLTW,2021-02-03,211.160004,211.270004,205.550003,206.199997,206.199997,751200

In [8]:
my_columns = ['Ticker','Standard Deviation']

In [9]:
final_dataframe = pd.DataFrame(columns = my_columns)

In [10]:
for ticker in tickers:
    data = statistics.stdev(thisdataframe.loc[ticker,'Close'])
    print(data)

3.766821098734821
10.261068986307299
4.666552691228848
15.824808600075206
4.495166160877508
16.451938677309123
3.4530767043777733
1.9772956802212054
4.250739532059521
12.299486266750472
9.170376694357477
9.324631282243041
17.105153989610834
4.704326743540721
13.212524479002733
5.089834949560586
8.998980379058672
30.000488112215788
15.951956348278573
10.181907027525217
16.6717670254134
28.851911307299016
2.485640927896683
3.9847746971384685
9.837103600651023
2.293114292261455
13.280338830051306
7.00111760773914
5.782226517224021
12.332657030549962
20.390102056896833
6.49815983584871
13.258011966761153
3.817552359519158
8.67377594629633
11.231039791564138
10.469509331321596
5.628162522039748
2.294352001021815
13.124575500076345

In [11]:
for ticker in tickers:
    data = statistics.variance(thisdataframe.loc[ticker,'Close'])
    print(data)

14.188941189873804
105.2895367417575
21.7767140200152
250.4245672290142
20.206518813898235
270.6662862419399
11.923738726316465
3.909698207021439
18.0687865694136
151.27736242598345
84.09580871641478
86.94874854978549
292.5862930082994
22.130690109992443
174.57080310824645
25.906419813768412
80.98164786268296
900.0292869712007
254.46491133738505
103.67123071716738
277.9478157496615
832.4327860842487
6.178410822435085
15.878429386954975
96.76860724994134
5.258373157373755
176.36739944096848
49.01564775739501
33.43414349648862
152.0944294331734
415.7562618906685
42.22608125223733
175.77488131078195
14.57370601767029
75.23438916654878
126.13625479969701
109.61062563863
31.67621337449282
5.264051104592808
172.25448205720426

In [13]:
for ticker in tickers:
    tickersearch = yf.Ticker(ticker)
    data = tickersearch.info['beta']
    print(data)

0.333511
0.807773
0.2508
0.828781
1.032017
0.778014
0.618996
0.578441
0.514407
1.332443
1.811099
0.312166
2.578256
0.354322
2.13287
0.334578
1.378335
1.491995
None
1.241596
0.746466
0.944503
3.302561
0.441302
1.088046
1.036764
2.870273
0.608858
0.840448
1.006302
0.179295
2.295168
0.646744
2.485139
0.804162
0.80096
1.399146
0.165955
1.000533
0.803571

In [14]:
my_columns = ['Ticker','Price','Standard Deviation','Beta','Variance']

In [15]:
final_dataframe = pd.DataFrame(columns = my_columns)

for ticker in tickers:
#     print(symbol_strings)
    batch_api_call_url = f'https://cloud.iexapis.com/stable/stock/market/batch/?types=stats,quote&symbols={ticker}&token=pk_98a9722b99584ee7b7c5ebed778846fc'
    data = requests.get(batch_api_call_url).json()
    data2 = statistics.mean(thisdataframe.loc[ticker,'Close'])
    data3 = statistics.stdev(thisdataframe.loc[ticker,'Close'])
    data4 = statistics.variance(thisdataframe.loc[ticker,'Close'])
    tickersearch = yf.Ticker(ticker)
    data5 = tickersearch.info['beta']
    for symbol in ticker.split(','):
        final_dataframe = final_dataframe.append(
                                        pd.Series([ticker, 
                                                   data[ticker]['quote']['latestPrice'],
                                                   data3,
                                                   data5,
                                                   data4
                                                   ], 
                                                  index = my_columns), 
                                        ignore_index = True)
        
    
final_dataframe

   Ticker    Price  Standard Deviation      Beta    Variance
0     LNT   49.590            3.766821  0.333511   14.188941
1     ALL  106.640           10.261069  0.807773  105.289537
2     AEE   74.080            4.666553    0.2508   21.776714
3     AON  205.940           15.824809  0.842582  250.424567
4      BK   41.910            4.495166  1.032017   20.206519
5     BDX  256.615           16.451939  0.778014  270.666286
6     BMY   62.000            3.453077  0.618996   11.923739
7     CPB   47.210            1.977296  0.578441    3.909698
8     CNC   60.340            4.250740  0.514407   18.068787
9     CVX   88.935           12.299486  1.332443  151.277362
10    COP   43.320            9.170377  1.811099   84.095809
11    CCI  163.380            9.324631  0.312166   86.948749
12   FANG   64.820           17.105154  2.578256  292.586293
13      D   72.730            4.704327  0.354322   22.130690
14    EOG   56.430           13.212524   2.13287  174.570803
15     ES   88.450            5.089835  0.334578   25.906420
16    XOM   47.960            8.998980  1.378335   80.981648
17    FLT  260.580           30.000488  1.491995  900.029287
18     GD  156.160           15.951956      None  254.464911
19    IBM  120.100           10.181907  1.241596  103.671231
20    LHX  184.660           16.671767  0.746466  277.947816
21    LMT  337.170           28.851911  0.944503  832.432786
22    MRO    7.770            2.485641  3.302561    6.178411
23    MRK   76.080            3.984775  0.441302   15.878429
24   NTRS   95.725            9.837104  1.088046   96.768607
25   NLOK   21.145            2.293114  1.036764    5.258373
26   NCLH   24.430           13.280339  2.870864  176.367399
27    PEP  139.090            7.001118  0.608858   49.015648
28     PM   82.890            5.782227  0.840448   33.434143
29    RTX   72.270           12.332657  1.019743  152.094429
30   SBAC  274.280           20.390102  0.179295  415.756262
31    SLB   24.715            6.498160  2.392209   42.226081
32    SRE  125.440           13.258012  0.646744  175.774881
33    FTI   11.495            3.817552  2.485139   14.573706
34    TSN   66.360            8.673776  0.804162   75.234389
35   VRSN  199.545           11.231040   0.80096  126.136255
36    VNO   37.680           10.469509  1.399146  109.610626
37    WEC   87.170            5.628163  0.165955   31.676213
38     WU   23.150            2.294352  1.000533    5.264051
39   WLTW  206.780           13.124576  0.768943  172.254482